var PERSONAL_RESTRINGIDO = [
	{
		"NRO": "1",
		"FULLNAME": "BUSTAMANTE SANCHEZ JORGE ANTONIO",
		"DNI": "10187341",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "2",
		"FULLNAME": "CAJACHAHUA CARLOS VICTOR MANUEL",
		"DNI": "03898267",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "3",
		"FULLNAME": "CHIRINOS SEVERINO ANA LUCIA",
		"DNI": "44157831",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "4",
		"FULLNAME": "DE LA CERNA GARCILAZO HANS KEVIN",
		"DNI": "70824800",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "5",
		"FULLNAME": "DEL CAMPO PRADA JORGE ALEJANDRO",
		"DNI": "42232316",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "6",
		"FULLNAME": "MERCADO ABANTO LUIS ALBERTO",
		"DNI": "09922330",
		"UNIDAD": "ADMIN.CENTRAL CALLAO",
		 
	},
	{
		"NRO": "7",
		"FULLNAME": "ANGULO ADRIANZEN CLAUDIA",
		"DNI": "70007762",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "8",
		"FULLNAME": "ARANA REYES QUEVEDO SARA SUSANA",
		"DNI": "09674675",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "9",
		"FULLNAME": "BARACCO ADRIANZEN FERNANDO FRANCISCO",
		"DNI": "41839875",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "10",
		"FULLNAME": "BRISSOLESE LLANOS FRANCA GIOCONDA",
		"DNI": "40345303",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "11",
		"FULLNAME": "BRONCANO MAMANI PIERINA MILUSKA",
		"DNI": "47662569",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "12",
		"FULLNAME": "CALDERON CURCIO CLAUDIA YOLANDA",
		"DNI": "25782681",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "13",
		"FULLNAME": "CARRASCO ROJAS YICELLA FELICIA",
		"DNI": "10388959",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "14",
		"FULLNAME": "CORNEJO PAREDES BEATRIZ KATHERINE",
		"DNI": "46633028",
		"UNIDAD": "ADMINISTRACION CENTRAL",
		 
	},
	{
		"NRO": "15",
		"FULLNAME": "DAVID REQUENA ANABEL CARLA",
		"DNI": "72647648",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "16",
		"FULLNAME": "ELGUERA FLORES ANDRES ALBERTO",
		"DNI": "25427965",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "17",
		"FULLNAME": "PAJUELO ORBEGOSO DENNIS WILLIAM",
		"DNI": "40957478",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "18",
		"FULLNAME": "RECAVARREN VILLALVA JEPP MANUEL",
		"DNI": "70328931",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "19",
		"FULLNAME": "VALIENTE HUERTA LILLIAM STEFANI",
		"DNI": "44092380",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "20",
		"FULLNAME": "VILLARREAL MIÑANO CARLO ANDRES",
		"DNI": "45346624",
		"UNIDAD": "ADMINISTRACION CENTRAL"
	},
	{
		"NRO": "21",
		"FULLNAME": "ARANDA EDUARDO EMILIO MIGUEL",
		"DNI": "32939952",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "22",
		"FULLNAME": "FUENTES MATALLANA VICTOR EDUARDO",
		"DNI": "40578060",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "23",
		"FULLNAME": "HUAYHUA HUAMAN CHRISTIAN ANDRES",
		"DNI": "10320075",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "24",
		"FULLNAME": "MAGUIÑA PALACIOS PAUL ANTHONY",
		"DNI": "44446294",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "25",
		"FULLNAME": "PRADO BARRANTES MERCEDES LILIANA",
		"DNI": "18097501",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "26",
		"FULLNAME": "REYES LIÑAN FILEMON",
		"DNI": "32792703",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "27",
		"FULLNAME": "VALENZUELA MARQUEZ PABLO JULIO",
		"DNI": "43338733",
		"UNIDAD": "ASTILLERO"
	},
	{
		"NRO": "28",
		"FULLNAME": "CUMPEN SEMINARIO DE ARAOZ NERY ADRIANA",
		"DNI": "08596832",
		"UNIDAD": "CHD"
	},
	{
		"NRO": "29",
		"FULLNAME": "GONZALES CHERO PIERR OMAR",
		"DNI": "45646442",
		"UNIDAD": "CHD"
	},
	{
		"NRO": "30",
		"FULLNAME": "ABRIL MERCADO LUIS ALBERTO",
		"DNI": "04635876",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "31",
		"FULLNAME": "APONTE D SOUZA BERNARDO ISAAC",
		"DNI": "",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "32",
		"FULLNAME": "AULLA ACUÑA JUAN CARLOS",
		"DNI": "09826451",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "33",
		"FULLNAME": "AVILA CHAVEZ KELYN MARILUZ",
		"DNI": "73081741",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "34",
		"FULLNAME": "CARBAJAL MONTES JUAN CARLOS",
		"DNI": "29572782",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "35",
		"FULLNAME": "CORCUERA REYES SEGUNDO AQUILES",
		"DNI": "32864735",
		"UNIDAD": "EMP. PESCA "
	},
	{
		"NRO": "36",
		"FULLNAME": "CRESPO RAMOS CARLOS RAFAEL",
		"DNI": "32983976",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "37",
		"FULLNAME": "CURO ZAVALETA TOMAS CHRISTIAN GIANCARLO",
		"DNI": "41278938",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "38",
		"FULLNAME": "GOMEZ ROMANI MANUEL",
		"DNI": "40714977",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "39",
		"FULLNAME": "MALCA SANCHEZ DELIA NATHALIE",
		"DNI": "47381932",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "40",
		"FULLNAME": "MORENO BAQUEDANO MIGUEL ALONSO",
		"DNI": "46812456",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "41",
		"FULLNAME": "OCHARAN AMADO EDILBERTO ALFREDO",
		"DNI": "30832389",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "42",
		"FULLNAME": "OVIEDO NUNJAR ROLANDO HILARIO",
		"DNI": "32966425",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "43",
		"FULLNAME": "PASCO MOYANO GUILLERMO ORLANDO",
		"DNI": "10868876",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "44",
		"FULLNAME": "QUEZADA NAJARRO ALVARO NORBERTO",
		"DNI": "30833765",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "45",
		"FULLNAME": "RODRIGUEZ CAMPOS FERNANDO SAUL",
		"DNI": "30820609",
		"UNIDAD": "EMP. PESCA "
	},
	{
		"NRO": "46",
		"FULLNAME": "RODRIGUEZ TORRES VICTOR MANUEL",
		"DNI": "41535277",
		"UNIDAD": "EMP. PESCA "
	},
	{
		"NRO": "47",
		"FULLNAME": "ROMERO FLORES JAIME LUIS",
		"DNI": "32930286",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "48",
		"FULLNAME": "SAMARITANO TARAZONA SERGIO",
		"DNI": "16011025",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "49",
		"FULLNAME": "TIRADO HURTADO GILMER RODOLFO",
		"DNI": "32988072",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "50",
		"FULLNAME": "VALDIVIEZO MERINO RODY LINO",
		"DNI": "09229555",
		"UNIDAD": "EMP. PESCA"
	},
	{
		"NRO": "51",
		"FULLNAME": "YZQUIERDO MERINO FELIX LORENZO",
		"DNI": "22265392",
		"UNIDAD": "EMP. PESCA "
	},
	{
		"NRO": "52",
		"FULLNAME": "ARONI BOY EDGAR JOSE ",
		"DNI": "22309852",
		"UNIDAD": "GERENTES "
	},
	{
		"NRO": "53",
		"FULLNAME": "NAMIHAS CASTRO RUBEN ABRAHAM",
		"DNI": "06669482",
		"UNIDAD": "GERENTES "
	},
	{
		"NRO": "54",
		"FULLNAME": "ROZAS OLIVERA HORTENCIA REBECA",
		"DNI": "10475677",
		"UNIDAD": "GERENTES "
	},
	{
		"NRO": "55",
		"FULLNAME": "ALVAREZ VENTURA ABDON ROLANDO",
		"DNI": "30487615",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "56",
		"FULLNAME": "APAZA PARI ROSENDO MERCEDES",
		"DNI": "02162261",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "57",
		"FULLNAME": "CARDENAS VALDIVIEZO LEDGAR EDAR",
		"DNI": "29545783",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "58",
		"FULLNAME": "CASTRO ZINANYUCA NILTON",
		"DNI": "80386260",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "59",
		"FULLNAME": "LOPEZ ZEGARRA JUAN FERNANDO",
		"DNI": "30402102",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "60",
		"FULLNAME": "MAMANI USEDO TIMOTEO",
		"DNI": "30405321",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "61",
		"FULLNAME": "MIRANDA MAMANI ENRIQUE ENCARNACION",
		"DNI": "30488511",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "62",
		"FULLNAME": "QUISPE SOTO JUAN FILOMENO",
		"DNI": "30487304",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "63",
		"FULLNAME": "VARGAS ALVARADO ARMENGOL PANFILO",
		"DNI": "09317669",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "64",
		"FULLNAME": "VASQUEZ CHIRINOS MOISES JAVIER",
		"DNI": "29407178",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "65",
		"FULLNAME": "VEGA FERNANDEZ GODOFREDO",
		"DNI": "30487446",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "66",
		"FULLNAME": "YAUYOS QUISPE ELISVAN",
		"DNI": "41017130",
		"UNIDAD": "PLANTA ATICO"
	},
	{
		"NRO": "67",
		"FULLNAME": "ABAD BENITES EUGENIO",
		"DNI": "03881708",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "68",
		"FULLNAME": "APACLLA ENRIQUEZ IVAN WILLIAMS",
		"DNI": "80214189",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "69",
		"FULLNAME": "BARTOLO CABANILLAS JOHM MULLER",
		"DNI": "40334015",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "70",
		"FULLNAME": "CALDERON SOCOLA ELBERT ALBERTO",
		"DNI": "25755306",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "71",
		"FULLNAME": "DAHGA VASQUEZ JIMMY WILLIAM",
		"DNI": "32928909",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "72",
		"FULLNAME": "ESPINOZA MELGAREJO JULIO RUBEN",
		"DNI": "45848855",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "73",
		"FULLNAME": "FRIAS DE LAS CASAS JUAN FRANCISCO",
		"DNI": "15986703",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "74",
		"FULLNAME": "GALLEGOS URRUTIA SAMUEL",
		"DNI": "22248088",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "75",
		"FULLNAME": "GARCIA REYES LUIS MANUEL",
		"DNI": "25824087",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "76",
		"FULLNAME": "HERBOZO REYNA ANIBAL",
		"DNI": "16006139",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	
	{
		"NRO": "78",
		"FULLNAME": "ROMERO RAMIREZ MARTIN ALEXANDER",
		"DNI": "25707017",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "79",
		"FULLNAME": "VARGAS SEMINARIO FRANZ",
		"DNI": "45833935",
		"UNIDAD": "PLANTA CALLAO NORTE"
	},
	{
		"NRO": "80",
		"FULLNAME": "ALAYO SERIN PEDRO",
		"DNI": "32799301",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "81",
		"FULLNAME": "ALVAREZ ORTEGA JESUS LUCIANO",
		"DNI": "32820455",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "82",
		"FULLNAME": "DE LA QUINTANA SAN MARTIN RAÚL NICOLAS",
		"DNI": "32945655",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "83",
		"FULLNAME": "DIAZ RODRIGUEZ PERCY ALFREDO",
		"DNI": "09151167",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "84",
		"FULLNAME": "MOLOCHE ECHEVARRIA NILTON ORLANDO",
		"DNI": "40461695",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "85",
		"FULLNAME": "MONZON CASANA LUIS ENRIQUE",
		"DNI": "32892645",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "86",
		"FULLNAME": "RIMARACHIN SALDAÑA JESUS MIGUEL",
		"DNI": "43598230",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "87",
		"FULLNAME": "RODRIGUEZ CHAVEZ LUIS SALVADOR",
		"DNI": "17811888",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "88",
		"FULLNAME": "RUIZ MARIÑOS SEGUNDO WILSON",
		"DNI": "32959340",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "89",
		"FULLNAME": "TORRES LULICHAC JAIME",
		"DNI": "33259647",
		"UNIDAD": "PLANTA CHIMBOTE"
	},
	{
		"NRO": "90",
		"FULLNAME": "AGUERO REYNA JUAN JOSE",
		"DNI": "40517363",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "91",
		"FULLNAME": "BARDALES BARDALES AGUSTIN FAUSTO",
		"DNI": "17806304",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "92",
		"FULLNAME": "CAPRISTAN GARCIA JUAN CARLOS",
		"DNI": "18161219",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "93",
		"FULLNAME": "LI SANCHEZ LUIS FELIPE",
		"DNI": "41171558",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "94",
		"FULLNAME": "MARENGO ROJAS EDUARDO ERNESTO",
		"DNI": "25681361",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "95",
		"FULLNAME": "NOLE CASTRO YVAN SEGUNDO",
		"DNI": "07402918",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "96",
		"FULLNAME": "QUINCHO PARIONA MAGNO EMILIANO",
		"DNI": "32541990",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "97",
		"FULLNAME": "RAMOS FLORES JOSE PIO",
		"DNI": "29531259",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "98",
		"FULLNAME": "RODRIGUEZ BUSTAMANTE DIONICIO",
		"DNI": "18863341",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "99",
		"FULLNAME": "ROQUE DE LA CRUZ HECTOR ANTONIO",
		"DNI": "43184801",
		"UNIDAD": "PLANTA MALABRIGO"
	},
	{
		"NRO": "100",
		"FULLNAME": "BOY PICHEN ZOZIMO SEGUNDO",
		"DNI": "18856358",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "101",
		"FULLNAME": "BUENO DAVILA DANTE FERNANDO",
		"DNI": "30821360",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "102",
		"FULLNAME": "CASTRO CONDORI EDGAR DAVID",
		"DNI": "00516288",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "103",
		"FULLNAME": "GUTIERREZ HUANCA RICARDO RAUL",
		"DNI": "25708277",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "104",
		"FULLNAME": "MARIN TORRES ILDEFONSO JAVIER",
		"DNI": "30828830",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "105",
		"FULLNAME": "ORTIZ ARENAS SANTIAGO IGNACIO",
		"DNI": "30844205",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "106",
		"FULLNAME": "PORTUGAL MANUEL EMILIO",
		"DNI": "30856772",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "107",
		"FULLNAME": "RIEGA ZEGARRA JAVIER HUGO",
		"DNI": "30854970",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "108",
		"FULLNAME": "ROJAS SEVINCHA EMILIANO LAUREANO",
		"DNI": "30825570",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "109",
		"FULLNAME": "TERNERO CHORA PRESVITERO ALEJANDRO",
		"DNI": "29382016",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "110",
		"FULLNAME": "TIQUE DURAN KALVI JULIO",
		"DNI": "04620020",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "111",
		"FULLNAME": "VALENZUELA CHACON JORGE EUSEBIO",
		"DNI": "30823222",
		"UNIDAD": "PLANTA MATARANI"
	},
	{
		"NRO": "112",
		"FULLNAME": "ALBARRACIN DIAZ ABEL FELIPE",
		"DNI": "22277541",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "113",
		"FULLNAME": "AÑANCA RAMOS JUAN ALBERTO",
		"DNI": "22248743",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "114",
		"FULLNAME": "BACA OSCA JOSE DUANER",
		"DNI": "29326048",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "115",
		"FULLNAME": "CARRIZALES TORRES JORGE MANUEL",
		"DNI": "22260785",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "116",
		"FULLNAME": "CORDOVA JARAMILLO SABINO JUAN",
		"DNI": "15635219",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "117",
		"FULLNAME": "DIAZ CUETO VICTOR RIGOBERTO",
		"DNI": "22280888",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "118",
		"FULLNAME": "ESCOBEDO CRUZ EDWIN MARCEL",
		"DNI": "32970215",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "119",
		"FULLNAME": "ESPINOZA ROBLES MARLY ANDREA",
		"DNI": "72421145",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "120",
		"FULLNAME": "GALLO ESTRADA LUIS ENRIQUE",
		"DNI": "04645479",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "121",
		"FULLNAME": "HUASHUAYLLO NAVARRO MAXIMO",
		"DNI": "22278908",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "122",
		"FULLNAME": "MARCOS CARRIZALES MELVI ANTONIA",
		"DNI": "43421854",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "123",
		"FULLNAME": "NAVARRO VITE JOSE ALFREDO",
		"DNI": "22258668",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "124",
		"FULLNAME": "VEGA ALCALA JORGE LUIS",
		"DNI": "09303207",
		"UNIDAD": "PLANTA PISCO NORTE"
	},
	{
		"NRO": "125",
		"FULLNAME": "CARRIZALES GUZMAN PEDRO ALFONSO",
		"DNI": "22240144",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "126",
		"FULLNAME": "GARCIA BAUTISTA CARLOS DANIEL",
		"DNI": "22258035",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "127",
		"FULLNAME": "GONZALES ANDRADE DANIEL ANTERO",
		"DNI": "22245390",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "128",
		"FULLNAME": "HERNANDEZ TATAJE JIMMY YAMBER",
		"DNI": "41021002",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "129",
		"FULLNAME": "HUACCALSAICO OYOLO LISSET CAROLINA",
		"DNI": "46697979",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "130",
		"FULLNAME": "HUAMAN RODRIGUEZ PABLO PEDRO",
		"DNI": "22265894",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "131",
		"FULLNAME": "ORELLANA TATAJE JOSE",
		"DNI": "22307032",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "132",
		"FULLNAME": "ORMEÑO ANDIA MARCOS MIGUEL",
		"DNI": "21423872",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "133",
		"FULLNAME": "QUISPE PAUCAR AMANCIO DIONICIO",
		"DNI": "21866731",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "134",
		"FULLNAME": "TIPIAN HERNANDEZ FELIX ENRIQUE",
		"DNI": "22260088",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "135",
		"FULLNAME": "YLAVE PONTE ERICK GUILLERMO",
		"DNI": "09960881",
		"UNIDAD": "PLANTA PISCO SUR"
	},
	{
		"NRO": "136",
		"FULLNAME": "CAMPOS GARCIA JUAN BENITO",
		"DNI": "22242076",
		"UNIDAD": "PLANTA PISCO SUR "
	},
	{
		"NRO": "137",
		"FULLNAME": "BERRU CHIRA FRANK YULIOR",
		"DNI": "09402992",
		"UNIDAD": "PLANTA PUCUSANA"
	},
	{
		"NRO": "138",
		"FULLNAME": "LARA CORNEJO JOSE MARTIN",
		"DNI": "40995183",
		"UNIDAD": "PLANTA PUCUSANA"
	},
	{
		"NRO": "139",
		"FULLNAME": "VEGAS NAVARRO MARCELA IMELDA",
		"DNI": "02774294",
		"UNIDAD": "PLANTA PUCUSANA"
	},
	{
		"NRO": "140",
		"FULLNAME": "MARTINEZ SILES ARMANDO MAURICIO",
		"DNI": "09526416",
		"UNIDAD": "PLANTA PUCUSANA "
	},
	{
		"NRO": "141",
		"FULLNAME": "ANTUNEZ DE LA QUINTANA IVAN OBDULIO",
		"DNI": "32959546",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "142",
		"FULLNAME": "CARRERA GARCIA GRECIA DEL ROCIO",
		"DNI": "70567984",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "143",
		"FULLNAME": "GAMBINI ROSALES RICARDO MAXIMO",
		"DNI": "32935718",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "144",
		"FULLNAME": "HIDALGO CAÑARI JULIO CESAR",
		"DNI": "32789356",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "145",
		"FULLNAME": "LECTOR CHU JOSE ANTONIO",
		"DNI": "32951957",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "146",
		"FULLNAME": "NUÑUVERO SAINEZ SABINO REYNALDO",
		"DNI": "32796322",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "147",
		"FULLNAME": "SALINAS CANO AURELIO MARGARITO",
		"DNI": "32887266",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "148",
		"FULLNAME": "VIDANGOS PEREZ JULIO GUSTAVO",
		"DNI": "41469115",
		"UNIDAD": "PLANTA SAMANCO"
	},
	{
		"NRO": "149",
		"FULLNAME": "ARDIAN VELASQUEZ ANGEL FERNANDO",
		"DNI": "15742256",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "150",
		"FULLNAME": "BIANCATO ALARCON ANTONIO",
		"DNI": "15711561",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "151",
		"FULLNAME": "CARO SILVA JACK JIMMY",
		"DNI": "41124043",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "152",
		"FULLNAME": "CERNA JARA ALEX GABRIEL",
		"DNI": "40615299",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "153",
		"FULLNAME": "DE PAZ ALBINO PASCUAL ALBERTO",
		"DNI": "15853553",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "154",
		"FULLNAME": "RAMOS AREVALO JOSE MANUEL",
		"DNI": "15640764",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "155",
		"FULLNAME": "REYES SALVADOR RUBEN GREGORIO",
		"DNI": "15719104",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "156",
		"FULLNAME": "SUCLUPE CAJUSOL JOSE SANTOS",
		"DNI": "16741313",
		"UNIDAD": "PLANTA SUPE"
	},
	{
		"NRO": "157",
		"FULLNAME": "CANALES COLLANTES ELIAS VICENTE",
		"DNI": "15716932",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "158",
		"FULLNAME": "CHUMBES MENDOZA HUGO BALTAZAR",
		"DNI": "15716003",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "159",
		"FULLNAME": "ESTEBAN COLLANTES ROSA ELIZABETH",
		"DNI": "15721292",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "160",
		"FULLNAME": "PALMA GARCIA WALDIR",
		"DNI": "15716339",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "161",
		"FULLNAME": "PALMA MONTAÑEZ ELMO PAUL",
		"DNI": "15716340",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "162",
		"FULLNAME": "PALMA RAMIREZ ALEXI ROMAIN",
		"DNI": "15718415",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "163",
		"FULLNAME": "PERALTA CHANG ALFREDO MARTINEZ",
		"DNI": "15716201",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "164",
		"FULLNAME": "SIANCAS MARTINEZ IDE JORGE",
		"DNI": "03653834",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "165",
		"FULLNAME": "SOSA TORRES JHIN EDER",
		"DNI": "45490403",
		"UNIDAD": "PLANTA VEGUETA"
	},
	{
		"NRO": "166",
		"FULLNAME": "ABANTO MUÑOZ FRANKLIN OMAR",
		"DNI": "80301995",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "167",
		"FULLNAME": "ABASALO SALAZAR FREDDY GAMENSON",
		"DNI": "10741528",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "168",
		"FULLNAME": "ACUÑA VILLAORDUÑA CONSTANTINO",
		"DNI": "16020008",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "169",
		"FULLNAME": "ALPISTE FLORES LUIS ALBERTO",
		"DNI": "15625242",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "170",
		"FULLNAME": "ALVAREZ CHAVEZ JOSE HERNAN",
		"DNI": "15987794",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "171",
		"FULLNAME": "ALVIÑO FLORES WALTER FEDERICO",
		"DNI": "32778245",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "172",
		"FULLNAME": "ANGULO DULANTO CARLOS",
		"DNI": "15755799",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "173",
		"FULLNAME": "ANTON PEREZ JOSE ROLANDO",
		"DNI": "40034338",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "174",
		"FULLNAME": "APARICIO VALLADARES ALEXIS",
		"DNI": "03500342",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "175",
		"FULLNAME": "AQUINO BAZAN JOSE SALVADOR",
		"DNI": "08485036",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "176",
		"FULLNAME": "ARANDA MEDINA JUAN CARLOS",
		"DNI": "15987034",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "177",
		"FULLNAME": "ARANGO GOMEZ JUAN IGNACIO",
		"DNI": "15610369",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "178",
		"FULLNAME": "ARANGURI ZEGARRA NICOLAS AGAPITO",
		"DNI": "32955595",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "179",
		"FULLNAME": "ARCE CERDA CARLOS ESTEBAN",
		"DNI": "10608692",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "180",
		"FULLNAME": "ARELLANO CARRION JHONY DANIEL",
		"DNI": "40590368",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "181",
		"FULLNAME": "AVALOS PEREDA JOSE ANTONIO",
		"DNI": "32989502",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "182",
		"FULLNAME": "BARRERA RUMICHE MIGUEL ANGEL",
		"DNI": "15985094",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "183",
		"FULLNAME": "BARRIENTOS SABALU PASTOR AMABLE",
		"DNI": "32117299",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "184",
		"FULLNAME": "BAZALAR SUAREZ FELIX ENRIQUE",
		"DNI": "15592521",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "185",
		"FULLNAME": "BERNALES ALEGRIA PEDRO ROQUE",
		"DNI": "06583728",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "186",
		"FULLNAME": "BIMINCHUMO BRON JULIO CESAR",
		"DNI": "32768055",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "187",
		"FULLNAME": "CABANILLAS CABANILLAS RAUL OMAR",
		"DNI": "25628312",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "188",
		"FULLNAME": "CALDERON MORAN HUMBERTO",
		"DNI": "03491604",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "189",
		"FULLNAME": "CAMONES BLANCO JESUS REYMUNDO",
		"DNI": "16008087",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "190",
		"FULLNAME": "CARRANZA CHINCHAY JOSE FAUSTINO",
		"DNI": "32838539",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "191",
		"FULLNAME": "CASSANO DIAZ MARTIN ALBERTO",
		"DNI": "22285268",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "192",
		"FULLNAME": "CASTAÑEDA AMANSIFUEN JOSE ANTONIO",
		"DNI": "18873046",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "193",
		"FULLNAME": "CASTILLO ALVERCA EDGAR RAUL",
		"DNI": "25791398",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "194",
		"FULLNAME": "CASTRO DELGADO PEDRO MIGUEL",
		"DNI": "15714400",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "195",
		"FULLNAME": "CASTRO TATAJE HECTOR NICOLAS",
		"DNI": "22284324",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "196",
		"FULLNAME": "CHANGANA BAZALAR HECTOR MANUEL",
		"DNI": "15640292",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "197",
		"FULLNAME": "CHANGANA CASTRO HERNAN ANDY",
		"DNI": "15639431",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "198",
		"FULLNAME": "CHAVEZ CORDOVA OSCAR ABILES",
		"DNI": "19223490",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "199",
		"FULLNAME": "CHINCHAY AYALA JESUS FELIX",
		"DNI": "25414650",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "200",
		"FULLNAME": "CHING YATACO NELSON PAUL",
		"DNI": "32984130",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "201",
		"FULLNAME": "CHUNGA FIESTAS FELICIANO",
		"DNI": "03465205",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "202",
		"FULLNAME": "CLAVIJO FERNANDEZ ANGEL NICOLAS",
		"DNI": "03493702",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "203",
		"FULLNAME": "CLAVIJO FERNANDEZ WILMER JAMBERTI",
		"DNI": "03499761",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "204",
		"FULLNAME": "CLAVIJO LOPEZ SANTOS JESUS",
		"DNI": "00325167",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "205",
		"FULLNAME": "CLAVIJO SANCHEZ JORGE ARMANDO",
		"DNI": "03464975",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "206",
		"FULLNAME": "COLLANTES LINARES JOSE PEDRO",
		"DNI": "32811639",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "207",
		"FULLNAME": "COLLAZOS GARCIA RICHARD NICZO",
		"DNI": "45419446",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "208",
		"FULLNAME": "COLLAZOS GONZALES NICZO",
		"DNI": "03491206",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "209",
		"FULLNAME": "CORONEL HOYOS NILTON ALY",
		"DNI": "32989744",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "210",
		"FULLNAME": "CRUZADO ASANZA JUAN CARLOS",
		"DNI": "03468201",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "211",
		"FULLNAME": "DE LAS CASAS ARAUJO ALBINO MANUEL",
		"DNI": "15977525",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "212",
		"FULLNAME": "DEL CARPIO AMOROS LUIS ANGELL",
		"DNI": "32971344",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "213",
		"FULLNAME": "DOMINGUEZ VEJARANO JUAN EDINZON",
		"DNI": "32814462",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "214",
		"FULLNAME": "ESCATE MENESES JORGE LUIS",
		"DNI": "22288201",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "215",
		"FULLNAME": "ESQUIVEL IRRAZABAL NELSON HUMBERTO",
		"DNI": "15853616",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "216",
		"FULLNAME": "FALCON BARRUETA EDUARDO RAFAEL",
		"DNI": "06769239",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "217",
		"FULLNAME": "FERNANDEZ VERA VIDAL",
		"DNI": "32977843",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "218",
		"FULLNAME": "FIESTAS CHUNGA EMILIO",
		"DNI": "03471069",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "219",
		"FULLNAME": "FLORES SILVA JOSE VICTOR",
		"DNI": "02790061",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "220",
		"FULLNAME": "GALLARDO ESPINOZA LUIS ALFREDO",
		"DNI": "32875903",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "221",
		"FULLNAME": "GALLEGOS BERMEJO JORGE DANIEL",
		"DNI": "29539128",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "222",
		"FULLNAME": "GALLO CASTRO WALTER AGUSTIN",
		"DNI": "32939820",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "223",
		"FULLNAME": "GONZALES OLAIBEL WILLIAN CARLOS",
		"DNI": "20563068",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "224",
		"FULLNAME": "GUEVARA AMORETTI CARLOS AUGUSTO",
		"DNI": "32911290",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "225",
		"FULLNAME": "GUEVARA GARCIA DELFIN",
		"DNI": "40079480",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "226",
		"FULLNAME": "HIDALGO ROSARIO JESUS ELIAS",
		"DNI": "16015560",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "227",
		"FULLNAME": "HIDALGO SERNA AUGUSTO RODOLFO",
		"DNI": "32907705",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "228",
		"FULLNAME": "HUANCA MACHACA RUBEN",
		"DNI": "04648798",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "229",
		"FULLNAME": "HUERTA BRANDAN RICARDO",
		"DNI": "32119478",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "230",
		"FULLNAME": "HUERTAS VALDIVIEZO SANTOS YBAN",
		"DNI": "44447794",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "231",
		"FULLNAME": "INFANTAS PINTO PEDRO MANUEL",
		"DNI": "15708014",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "232",
		"FULLNAME": "JACINTO LIMAS CATALINO",
		"DNI": "03491598",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "233",
		"FULLNAME": "JIMENEZ GUERRERO PABLO ALFONSO",
		"DNI": "25480516",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "234",
		"FULLNAME": "LEON GUTIERREZ HEBER JORGE",
		"DNI": "15755956",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "235",
		"FULLNAME": "LEON GUTIERREZ HELBERT JULIO",
		"DNI": "15755431",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "236",
		"FULLNAME": "LEON TARIFEÑO SEBASTIAN TEODORO",
		"DNI": "25623808",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "237",
		"FULLNAME": "LLAJA VEGA WILMER",
		"DNI": "18988279",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "238",
		"FULLNAME": "LOPEZ PINEDO JAMER WILIAM",
		"DNI": "09945262",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "239",
		"FULLNAME": "MACHADO MIRANDA BENITO JUAN",
		"DNI": "32889510",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "240",
		"FULLNAME": "MARCIAL PLACENCIA LUIS ALBERTO",
		"DNI": "15853832",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "241",
		"FULLNAME": "MARREROS MENDOZA JUAN DIONICIO",
		"DNI": "03504601",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "242",
		"FULLNAME": "MARTINEZ TOLEDO TEODORO",
		"DNI": "15640068",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "243",
		"FULLNAME": "MESSARINA CUYA CESAR HUMBERTO",
		"DNI": "32961187",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "244",
		"FULLNAME": "MIMBELA REYES MIGUEL ANGEL",
		"DNI": "40242658",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "245",
		"FULLNAME": "MINAYA BAZALAR ROBERT HENRY",
		"DNI": "15725099",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "246",
		"FULLNAME": "MIÑOPE CHANCAFE MARCO ANTONIO",
		"DNI": "16588853",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "247",
		"FULLNAME": "MOGOLLON OLAYA MANUEL",
		"DNI": "03866357",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "248",
		"FULLNAME": "MONCADA JAICO RICARDO",
		"DNI": "17914629",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "249",
		"FULLNAME": "MORALES FIESTAS OCTAVIO",
		"DNI": "17560915",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "250",
		"FULLNAME": "MORAN MOGOLLON MANUEL ALBERTO",
		"DNI": "03867855",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "251",
		"FULLNAME": "MOYA PEREZ JUAN WILFREDO",
		"DNI": "09643177",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "252",
		"FULLNAME": "MUÑOZ MIRANDA ROBERT HERLESS",
		"DNI": "40325675",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "253",
		"FULLNAME": "NAPURI FERNANDEZ ALAN JUNIOR",
		"DNI": "41800544",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "254",
		"FULLNAME": "NAVARRETE ORMEÑO TOBIAS JOSE SANTOS",
		"DNI": "22289371",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "255",
		"FULLNAME": "OYOLA CAVERO MARCOS ANTONIO",
		"DNI": "15639441",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "256",
		"FULLNAME": "PAIBA CHICLAYO VICTOR LINDERMAN",
		"DNI": "03489900",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "257",
		"FULLNAME": "PAJUELO SALINAS JAIME ANATOLIO",
		"DNI": "15704172",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "258",
		"FULLNAME": "PANTA AYALA CLAUDIO",
		"DNI": "03470442",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "259",
		"FULLNAME": "PANTA PAIBA JULIO",
		"DNI": "03463796",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "260",
		"FULLNAME": "PARDO FIGUEROA ARIAS EDUARDO",
		"DNI": "01311762",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "261",
		"FULLNAME": "PAUCAR AGUIRRE RAUL ANGEL",
		"DNI": "21859090",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "262",
		"FULLNAME": "PEÑA PEÑA PABLO ANDRES",
		"DNI": "32979192",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "263",
		"FULLNAME": "PEREDA LOYAGA LUIS OLIVORIO",
		"DNI": "32857621",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "264",
		"FULLNAME": "PEREZ ALVAREZ MARCO ANTONIO",
		"DNI": "15738333",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "265",
		"FULLNAME": "PERICHE FIESTAS MARTIN",
		"DNI": "02834020",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "266",
		"FULLNAME": "PERICHE GALAN GENARO",
		"DNI": "02742781",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "267",
		"FULLNAME": "PERICHE PERICHE MARINO MARIO",
		"DNI": "03470471",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "268",
		"FULLNAME": "QUIROGA FIESTAS WALTER FRANCISCO",
		"DNI": "43505021",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "269",
		"FULLNAME": "RAMIREZ DIAZ PACO ARMIN",
		"DNI": "15639336",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "270",
		"FULLNAME": "RAMIREZ VILLEGAS LUIS ALBERTO",
		"DNI": "15715046",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "271",
		"FULLNAME": "RAMOS CAVERO JUAN",
		"DNI": "15638482",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "272",
		"FULLNAME": "RAMOS MATUMAY FREDY MARTIN",
		"DNI": "15379993",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "273",
		"FULLNAME": "RAMOS URBINA CARLOS ANTONIO",
		"DNI": "15647613",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "274",
		"FULLNAME": "REATEGUI ARISTONDO SERGIO FRANCISCO",
		"DNI": "25651122",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "275",
		"FULLNAME": "REVOLLEDO JIMENEZ NAPOLEON",
		"DNI": "32119281",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "276",
		"FULLNAME": "REYNA GARCIA HENRY HUGO",
		"DNI": "16006268",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "277",
		"FULLNAME": "REYNA NOVELLA ANTONIO MIGUEL",
		"DNI": "16007466",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "278",
		"FULLNAME": "REYNOSO APAZA ISRAEL ENRIQUE",
		"DNI": "04645355",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "279",
		"FULLNAME": "ROBLEDO HERRERA JOHN CHRISTIAN",
		"DNI": "25824310",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "280",
		"FULLNAME": "ROSADO RODRIGUEZ MARTIN GUILLERMO",
		"DNI": "32802559",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "281",
		"FULLNAME": "SAAVEDRA JIMENEZ WILSON",
		"DNI": "32848769",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "282",
		"FULLNAME": "SALINAS PADILLA NIL MEDARDO",
		"DNI": "16007936",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "283",
		"FULLNAME": "SANCHEZ GUERRERO LUIS CARLOS",
		"DNI": "29627210",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "284",
		"FULLNAME": "SARMIENTO SALINAS MAURO",
		"DNI": "32964059",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "285",
		"FULLNAME": "SERNAQUE CHIROQUE SANTOS",
		"DNI": "03492807",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "286",
		"FULLNAME": "SILVA SOTELO FERNANDO JUNIORS",
		"DNI": "40902643",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "287",
		"FULLNAME": "SOLANO POLO VICTOR ANTONIO",
		"DNI": "32892016",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "288",
		"FULLNAME": "TAVARA MIÑAN FERNANDO JAVIER",
		"DNI": "32955916",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "289",
		"FULLNAME": "TEJADA URETA PABLO GREGORIO",
		"DNI": "15601141",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "290",
		"FULLNAME": "TORRES GARCIA JOSE ANTONIO",
		"DNI": "22302147",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "291",
		"FULLNAME": "URIBE JORGE JUAN CARLOS",
		"DNI": "32958327",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "292",
		"FULLNAME": "VALDIVIESO CAMPOVERDE LUIS ALBERTO",
		"DNI": "32954662",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "293",
		"FULLNAME": "VALENCIA PAZOS JOSE MARIO",
		"DNI": "16023854",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "294",
		"FULLNAME": "VARGAS PACORA JOSE ALFREDO",
		"DNI": "15586781",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "295",
		"FULLNAME": "VASQUEZ SOLANO JULY MOHASIR",
		"DNI": "32985214",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "296",
		"FULLNAME": "VILCHEZ FIESTAS EMETERIO",
		"DNI": "25599670",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "297",
		"FULLNAME": "VILCHEZ VILCHEZ GREGORIO",
		"DNI": "02719533",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "298",
		"FULLNAME": "VILLANUEVA RAMOS VICTOR SAMUEL",
		"DNI": "32928428",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "299",
		"FULLNAME": "VIRU GAVIRIA ALEXANDER MICHAEL",
		"DNI": "15640765",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "300",
		"FULLNAME": "YARLEQUE CASTRO EDGAR WILLIAMS",
		"DNI": "40395058",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "301",
		"FULLNAME": "YON RAMOS CESAR ALFONSO",
		"DNI": "41101165",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "302",
		"FULLNAME": "ZULOAGA VARGAS WILMER OSCAR",
		"DNI": "15713816",
		"UNIDAD": "TRIPULANTES"
	},
	{
		"NRO": "303",
		"FULLNAME": "ZUÑIGA HUERTAS MANUEL ANGEL",
		"DNI": "15987561",
		"UNIDAD": "TRIPULANTES"
	}
]